console.log("This is First line ");
console.log("This is Second line ");
console.log("This is Third line ");
console.log("This is Fourth line ");
console.log("This is Fifth line ");
let a = 10;
console.log("This is Seventh line From Branch semi");
console.log("This is Eighth line ");
console.log("This is Ninth line ");
console.log("This is Tenth line ");
